### ISSUE TITLE
v1 node name dependency

### ISSUE THREAD

**Issue by nkinkade** [m-lab/reboot-service#35]
There is still at least one more v1 node name dependency:

https://github.com/m-lab/reboot-service/blob/master/reboot/handler.go#L212

There also appear to be two functions that still return v1 names:

https://github.com/m-lab/reboot-service/blob/master/reboot/handler.go#L224
https://github.com/m-lab/reboot-service/blob/master/reboot/handler.go#L232

@robertodauria: Fixing L212 above is easy, but it wasn't immediately clear to me what to do about the two functions that still return v1 names, or if it even matters.

**Comment by nkinkade** [comment]
@robertodauria: What do you think we can do here?

**Comment by robertodauria** [comment]
@nkinkade I believe PR (https://github.com/m-lab/reboot-service/pull/36) fixed this -- please feel free to reopen if that's not the case.
