### ISSUE TITLE
Prometheus metric labels and values seem incorrect

### ISSUE THREAD

**Issue by nkinkade** [m-lab/reboot-service#39]
The reboot-api exports the metric `reboot_e2e_result`. When it is able to connect to a DRAC successfully, you get a metric like:

```
reboot_e2e_result{status="ok"} 1
```

When a connection attempt fails you get a metric like:

```
reboot_e2e_result{status="connection_failed"} 0
```

In either case, when one of these exists for a node, the other metric disappears. The semantics of  the labels seem a little off. When the `status="connection_failed"` I would expect the value to be 1, not 0. Additionally, it would be nice if the metric did disappear when the status changed.

Would a better way to handle this be when things are good we get:

```
reboot_e2e_result{status="ok"} 1
```

... and when they are bad we get:

```
reboot_e2e_result{status="ok"} 0
```

??

**Comment by pboothe** [comment]
Metric should be refactored into two counters: `reboot_e2e_successes` and `reboot_e2e_failures{status="..."}`
